version: '3'

services:
  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_pw_shh
      MYSQL_DATABASE: mall
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
  web:
    build: .
    container_name: php_web
    depends_on:
      - database
    ports:
      - "80:80"
    stdin_open: true
    links: 
      - database
    tty: true