version: '3'

services:
  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_pw_shh
      MYSQL_DATABASE: posts
  web:
    build: .
    container_name: php_web
    depends_on:
      - database
    ports:
      - "80:80"
    stdin_open: true
    volumes:
      - "./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql"
    links: 
      - database
    tty: true